spring.application.name=ministere-app

# ==========================================
# PORT RENDER
# ==========================================
server.port=${PORT:8080}

# ==========================================
# POSTGRESQL
# Les valeurs viennent des variables Render
# ==========================================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ==========================================
# ENCODAGE
# ==========================================
spring.sql.init.encoding=UTF-8

# ==========================================
# EMAIL (pour les codes de confirmation)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true